// =========================================================================
// 1. ENUMS Y TIPOS EXCLUSIVOS DE PRISMA (MAPEADOS UNO A UNO SIN OMISIONES)
// =========================================================================

export enum NurseRestrictionTypes {
    NO_NIGHT_SHIFTS = "NO_NIGHT_SHIFTS",
    ONLY_NIGHT_SHIFTS = "ONLY_NIGHT_SHIFTS",
    ONLY_DAY_SHIFTS = "ONLY_DAY_SHIFTS",
    ONLY_MORNING_SHIFTS = "ONLY_MORNING_SHIFTS",
    ONLY_AFTERNOON_SHIFTS = "ONLY_AFTERNOON_SHIFTS",
    NO_WEEKENDS = "NO_WEEKENDS",
    WEEKENDS_ONLY = "WEEKENDS_ONLY",
    NO_HOLIDAYS = "NO_HOLIDAYS",
    NO_DOUBLE_SHIFTS = "NO_DOUBLE_SHIFTS",
    NO_CONSECUTIVE_SHIFTS = "NO_CONSECUTIVE_SHIFTS",
    NO_NOCHES_CONSECUTIVAS = "NO_CONSECUTIVE_NIGHTS", // Mapeado a la base de datos
    LIMITED_CONSECUTIVE_DAYS = "LIMITED_CONSECUTIVE_DAYS",
    LIMITED_HOURS = "LIMITED_HOURS",
    NO_OVERTIME = "NO_OVERTIME",
    MAX_40_HOURS_WEEK = "MAX_40_HOURS_WEEK",
    MAX_8_HOURS_DAY = "MAX_8_HOURS_DAY",
    REDUCED_WORKLOAD = "REDUCED_WORKLOAD",
    PART_TIME_ONLY = "PART_TIME_ONLY",
    PREGNANCY_RESTRICTION = "PREGNANCY_RESTRICTION",
    MEDICAL_RESTRICTION = "MEDICAL_RESTRICTION",
    NO_HEAVY_PATIENTS = "NO_HEAVY_PATIENTS",
    NO_STANDING_LONG_HOURS = "NO_STANDING_LONG_HOURS",
    FATIGUE_RECOVERY = "FATIGUE_RECOVERY",
    POST_SURGERY_LIMITATION = "POST_SURGERY_LIMITATION",
    TEMPORARY_HEALTH_LIMITATION = "TEMPORARY_HEALTH_LIMITATION",
    CHRONIC_CONDITION = "CHRONIC_CONDITION",
    MENTAL_HEALTH_RESTRICTION = "MENTAL_HEALTH_RESTRICTION",
    ONLY_ICU = "ONLY_ICU",
    ONLY_ER = "ONLY_ER",
    ONLY_PEDIATRICS = "ONLY_PEDIATRICS",
    NO_ICU = "NO_ICU",
    NO_ER = "NO_ER",
    NO_SURGERY = "NO_SURGERY",
    RESTRICTED_DEPARTMENT_ACCESS = "RESTRICTED_DEPARTMENT_ACCESS",
    UNDER_TRAINING = "UNDER_TRAINING",
    SUPERVISION_REQUIRED = "SUPERVISION_REQUIRED",
    NO_CRITICAL_PATIENTS = "NO_CRITICAL_PATIENTS",
    JUNIOR_LIMITATION = "JUNIOR_LIMITATION",
    INTERN_RESTRICTION = "INTERN_RESTRICTION",
    PROBATION_PERIOD = "PROBATION_PERIOD",
    UNION_RESTRICTION = "UNION_RESTRICTION",
    CONTRACT_LIMITATION = "CONTRACT_LIMITATION",
    TEMPORARY_EMPLOYEE = "TEMPORARY_EMPLOYEE",
    AGENCY_STAFF_ONLY = "AGENCY_STAFF_ONLY",
    NO_EXTRA_SHIFTS = "NO_EXTRA_SHIFTS",
    FIXED_SCHEDULE_ONLY = "FIXED_SCHEDULE_ONLY",
    NO_EMERGENCY_COVERAGE = "NO_EMERGENCY_COVERAGE",
    LAST_MINUTE_UNAVAILABLE = "LAST_MINUTE_UNAVAILABLE",
    CANNOT_BE_ON_CALL = "CANNOT_BE_ON_CALL",
    RESTRICTED_MOBILITY = "RESTRICTED_MOBILITY",
    NO_FLOATING = "NO_FLOATING",
    HIGH_FATIGUE_RISK = "HIGH_FATIGUE_RISK",
    LABOR_LAW_LIMITATION = "LABOR_LAW_LIMITATION",
    MINIMUM_REST_REQUIRED = "MINIMUM_REST_REQUIRED",
    MAX_MONTHLY_HOURS_REACHED = "MAX_MONTHLY_HOURS_REACHED",
    LICENSE_RESTRICTION = "LICENSE_RESTRICTION",
    CERTIFICATION_EXPIRED = "CERTIFICATION_EXPIRED",
    TEMPORARY_AVAILABILITY = "TEMPORARY_AVAILABILITY",
    VACATION_TRANSITION = "VACATION_TRANSITION",
    RETURNING_FROM_LEAVE = "RETURNING_FROM_LEAVE",
    RECENT_OVERTIME_BLOCK = "RECENT_OVERTIME_BLOCK",
    HIGH_RISK_PATIENT_RESTRICTION = "HIGH_RISK_PATIENT_RESTRICTION",
    INFECTIOUS_AREA_RESTRICTION = "INFECTIOUS_AREA_RESTRICTION",
    ISOLATION_AREA_RESTRICTION = "ISOLATION_AREA_RESTRICTION",
    BIOHAZARD_LIMITATION = "BIOHAZARD_LIMITATION"
}

export enum NurseRestrictionDescriptions {
    NO_PUEDE_HACER_AMANECIDAS = "NO_PUEDE_HACER_AMANECIDAS",
    SOLO_TRABAJA_NOCHES = "SOLO_TRABAJA_NOCHES",
    SOLO_TRABAJA_DIAS = "SOLO_TRABAJA_DIAS",
    SOLO_MAÑANAS = "SOLO_MAÑANAS",
    SOLO_TARDES = "SOLO_TARDES",
    NO_TRABAJA_FINES_DE_SEMANA = "NO_TRABAJA_FINES_DE_SEMANA",
    SOLO_FINES_DE_SEMANA = "SOLO_FINES_DE_SEMANA",
    NO_TRABAJA_FERIADOS = "NO_TRABAJA_FERIADOS",
    NO_PUEDE_HACER_DOBLE_TURNO = "NO_PUEDE_HACER_DOBLE_TURNO",
    NO_TURNOS_SEGUIDOS = "NO_TURNOS_SEGUIDOS",
    NO_NOCHES_CONSECUTIVAS = "NO_NOCHES_CONSECUTIVAS",
    MAXIMO_DIAS_SEGUIDOS = "MAXIMO_DIAS_SEGUIDOS",
    HORAS_LIMITADAS = "HORAS_LIMITADAS",
    NO_OVERTIME = "NO_OVERTIME",
    MAXIMO_40H = "MAXIMO_40H",
    MAXIMO_8H_POR_DIA = "MAXIMO_8H_POR_DIA",
    CARGA_REDUCIDA = "CARGA_REDUCIDA",
    SOLO_MEDIO_TIEMPO = "SOLO_MEDIO_TIEMPO",
    RESTRICCION_EMBARAZO = "RESTRICCION_EMBARAZO",
    RESTRICCION_MEDICA_GENERAL = "RESTRICCION_MEDICA_GENERAL",
    NO_PACIENTES_PESADOS = "NO_PACIENTES_PESADOS",
    NO_LARGAS_HORAS_DE_PIE = "NO_LARGAS_HORAS_DE_PIE",
    RECUPERACION_FISICA = "RECUPERACION_FISICA",
    RECUPERACION_CIRUGIA = "RECUPERACION_CIRUGIA",
    RESTRICCION_TEMPORAL = "RESTRICCION_TEMPORAL",
    CONDICION_CRONICA = "CONDICION_CRONICA",
    SALUD_MENTAL = "SALUD_MENTAL",
    SOLO_UCI = "SOLO_UCI",
    SOLO_EMERGENCIAS = "SOLO_EMERGENCIAS",
    SOLO_PEDIATRIA = "SOLO_PEDIATRIA",
    NO_UCI = "NO_UCI",
    NO_EMERGENCIAS = "NO_EMERGENCIAS",
    NO_CIRUGIA = "NO_CIRUGIA",
    ACCESO_LIMITADO = "ACCESO_LIMITADO",
    EN_ENTRENAMIENTO = "EN_ENTRENAMIENTO",
    REQUIERE_SUPERVISION = "REQUIERE_SUPERVISION",
    NO_CRITICOS = "NO_CRITICOS",
    RESTRICCION_JUNIOR = "RESTRICCION_JUNIOR",
    PASANTIA = "PASANTIA",
    PERIODO_PRUEBA = "PERIODO_PRUEBA",
    SINDICATO = "SINDICATO",
    RESTRICCION_CONTRACTUAL = "RESTRICCION_CONTRACTUAL",
    TEMPORAL = "TEMPORAL",
    PERSONAL_EXTERNO = "PERSONAL_EXTERNO",
    NO_TURNOS_EXTRA = "NO_TURNOS_EXTRA",
    HORARIO_FIJO = "HORARIO_FIJO",
    NO_COBERTURA_URGENTE = "NO_COBERTURA_URGENTE",
    NO_DISPONIBILIDAD_URGENTE = "NO_DISPONIBILIDAD_URGENTE",
    NO_GUARDIAS = "NO_GUARDIAS",
    NO_MOVERSE_ENTRE_DEPARTAMENTOS = "NO_MOVERSE_ENTRE_DEPARTAMENTOS",
    NO_SOPORTE_CRUZADO = "NO_SOPORTE_CRUZADO",
    ALTO_RIESGO_FATIGA = "ALTO_RIESGO_FATIGA",
    RESTRICCION_LEGAL = "RESTRICCION_LEGAL",
    DESCANSO_OBLIGATORIO = "DESCANSO_OBLIGATORIO",
    LIMITE_MENSUAL_ALCANZADO = "LIMITE_MENSUAL_ALCANZADO",
    LICENCIA_LIMITADA = "LICENCIA_LIMITADA",
    CERTIFICACION_VENCIDA = "CERTIFICACION_VENCIDA",
    DISPONIBILIDAD_TEMPORAL = "DISPONIBILIDAD_TEMPORAL",
    CERCA_VACACIONES = "CERCA_VACACIONES",
    REINTEGRACION = "REINTEGRACION",
    BLOQUEADA_POR_OVERTIME_RECIENTE = "BLOQUEADA_POR_OVERTIME_RECIENTE",
    NO_PACIENTES_ALTO_RISGO = "NO_PACIENTES_ALTO_RISGO",
    NO_AREAS_INFECCIOSAS = "NO_AREAS_INFECCIOSAS",
    NO_AISLAMIENTO = "NO_AISLAMIENTO",
    RESTRICCION_BIOSEGURIDAD = "RESTRICCION_BIOSEGURIDAD"
}

// Mapeo amigable para el usuario en la interfaz
export const RestrictionLabels: Record<NurseRestrictionTypes, string> = {
    [NurseRestrictionTypes.NO_NIGHT_SHIFTS]: "No Nocturnidad (No Amanecidas)",
    [NurseRestrictionTypes.ONLY_NIGHT_SHIFTS]: "Solo Turnos Nocturnos",
    [NurseRestrictionTypes.ONLY_DAY_SHIFTS]: "Solo Turnos Diurnos",
    [NurseRestrictionTypes.ONLY_MORNING_SHIFTS]: "Solo Turno Mañana",
    [NurseRestrictionTypes.ONLY_AFTERNOON_SHIFTS]: "Solo Turno Tarde",
    [NurseRestrictionTypes.NO_WEEKENDS]: "No Fines de Semana",
    [NurseRestrictionTypes.WEEKENDS_ONLY]: "Solo Fines de Semana",
    [NurseRestrictionTypes.NO_HOLIDAYS]: "No trabaja Feriados",
    [NurseRestrictionTypes.NO_DOUBLE_SHIFTS]: "Prohibido Doble Turno",
    [NurseRestrictionTypes.NO_CONSECUTIVE_SHIFTS]: "No Turnos Consecutivos",
    [NurseRestrictionTypes.NO_NOCHES_CONSECUTIVAS]: "No Noches Consecutivas",
    [NurseRestrictionTypes.LIMITED_CONSECUTIVE_DAYS]: "Días Consecutivos Limitados",
    [NurseRestrictionTypes.LIMITED_HOURS]: "Horas de Trabajo Limitadas",
    [NurseRestrictionTypes.NO_OVERTIME]: "No Horas Extras (Overtime)",
    [NurseRestrictionTypes.MAX_40_HOURS_WEEK]: "Máximo 40 Horas Semanales",
    [NurseRestrictionTypes.MAX_8_HOURS_DAY]: "Máximo 8 Horas por Día",
    [NurseRestrictionTypes.REDUCED_WORKLOAD]: "Carga de Trabajo Reducida",
    [NurseRestrictionTypes.PART_TIME_ONLY]: "Solo Medio Tiempo (Part-time)",
    [NurseRestrictionTypes.PREGNANCY_RESTRICTION]: "Restricción por Embarazo",
    [NurseRestrictionTypes.MEDICAL_RESTRICTION]: "Restricción Médica General",
    [NurseRestrictionTypes.NO_HEAVY_PATIENTS]: "No Cargar Pacientes Pesados",
    [NurseRestrictionTypes.NO_STANDING_LONG_HOURS]: "No Largas Horas de Pie",
    [NurseRestrictionTypes.FATIGUE_RECOVERY]: "Recuperación por Fatiga Crónica",
    [NurseRestrictionTypes.POST_SURGERY_LIMITATION]: "Limitación Post-Cirugía",
    [NurseRestrictionTypes.TEMPORARY_HEALTH_LIMITATION]: "Limitación de Salud Temporal",
    [NurseRestrictionTypes.CHRONIC_CONDITION]: "Condición de Salud Crónica",
    [NurseRestrictionTypes.MENTAL_HEALTH_RESTRICTION]: "Restricción por Salud Mental",
    [NurseRestrictionTypes.ONLY_ICU]: "Solo Unidad de Cuidados Intensivos (UCI)",
    [NurseRestrictionTypes.ONLY_ER]: "Solo Emergencias (ER)",
    [NurseRestrictionTypes.ONLY_PEDIATRICS]: "Solo Pediatría",
    [NurseRestrictionTypes.NO_ICU]: "Restricción de Acceso a UCI",
    [NurseRestrictionTypes.NO_ER]: "Restricción de Acceso a Emergencias",
    [NurseRestrictionTypes.NO_SURGERY]: "No Quirófano / Cirugía",
    [NurseRestrictionTypes.RESTRICTED_DEPARTMENT_ACCESS]: "Acceso Restringido a Departamentos",
    [NurseRestrictionTypes.UNDER_TRAINING]: "En Entrenamiento (Capacitación)",
    [NurseRestrictionTypes.SUPERVISION_REQUIRED]: "Requiere Supervisión Directa",
    [NurseRestrictionTypes.NO_CRITICAL_PATIENTS]: "No Atender Pacientes Críticos",
    [NurseRestrictionTypes.JUNIOR_LIMITATION]: "Limitación por Perfil Junior",
    [NurseRestrictionTypes.INTERN_RESTRICTION]: "Restricción de Pasante / Interno",
    [NurseRestrictionTypes.PROBATION_PERIOD]: "Periodo de Prueba Activo",
    [NurseRestrictionTypes.UNION_RESTRICTION]: "Restricción por Convenio Sindical",
    [NurseRestrictionTypes.CONTRACT_LIMITATION]: "Limitación por Cláusula Contractual",
    [NurseRestrictionTypes.TEMPORARY_EMPLOYEE]: "Empleado Temporal",
    [NurseRestrictionTypes.AGENCY_STAFF_ONLY]: "Personal de Agencia Externa",
    [NurseRestrictionTypes.NO_EXTRA_SHIFTS]: "No Asignar Turnos Extra",
    [NurseRestrictionTypes.FIXED_SCHEDULE_ONLY]: "Horario Fijo Únicamente",
    [NurseRestrictionTypes.NO_EMERGENCY_COVERAGE]: "Exento de Coberturas de Urgencia",
    [NurseRestrictionTypes.LAST_MINUTE_UNAVAILABLE]: "No Disponible para Llamados de Último Minuto",
    [NurseRestrictionTypes.CANNOT_BE_ON_CALL]: "No puede hacer Guardias Pasivas (On-Call)",
    [NurseRestrictionTypes.RESTRICTED_MOBILITY]: "Movilidad Física Restringida",
    [NurseRestrictionTypes.NO_FLOATING]: "No Flotar (No mover entre sedes)",
    [NurseRestrictionTypes.HIGH_FATIGUE_RISK]: "Alto Riesgo de Fatiga Laboral",
    [NurseRestrictionTypes.LABOR_LAW_LIMITATION]: "Limitación por Ley de Trabajo Nacional",
    [NurseRestrictionTypes.MINIMUM_REST_REQUIRED]: "Descanso Mínimo Obligatorio",
    [NurseRestrictionTypes.MAX_MONTHLY_HOURS_REACHED]: "Límite de Horas Mensuales Alcanzado",
    [NurseRestrictionTypes.LICENSE_RESTRICTION]: "Licencia Médica Restringida",
    [NurseRestrictionTypes.CERTIFICATION_EXPIRED]: "Certificación Técnica Vencida",
    [NurseRestrictionTypes.TEMPORARY_AVAILABILITY]: "Disponibilidad Temporal Reducida",
    [NurseRestrictionTypes.VACATION_TRANSITION]: "Transición por Vacaciones Cercanas",
    [NurseRestrictionTypes.RETURNING_FROM_LEAVE]: "Reintegración por Licencia de Larga Duración",
    [NurseRestrictionTypes.RECENT_OVERTIME_BLOCK]: "Bloqueado por Exceso de Overtime Reciente",
    [NurseRestrictionTypes.HIGH_RISK_PATIENT_RESTRICTION]: "No atender Pacientes de Alto Riesgo",
    [NurseRestrictionTypes.INFECTIOUS_AREA_RESTRICTION]: "No ingresar a Áreas Infecciosas",
    [NurseRestrictionTypes.ISOLATION_AREA_RESTRICTION]: "No ingresar a Áreas de Aislamiento",
    [NurseRestrictionTypes.BIOHAZARD_LIMITATION]: "Restricción por Riesgo Biológico"
};