// @/modules/schedules/types.ts

export type ScheduleStatus = "DRAFT" | "GENERATING" | "GENERATED" | "UNDER_REVIEW" | "APPROVED" | "PUBLISHED" | "ARCHIVED" | "CANCELLED";
export type ScheduleEntryStatus = "ASSIGNED" | "CONFIRMED" | "PENDING" | "CANCELLED" | "REPLACED" | "OPEN";

export interface Shift {
    id: string;
    organizationId: string;
    departmentId: string;
    name: string;
    code: string;
    type: string;
    startTime: string; // ISO String (ej: "2026-06-01T11:00:00.000Z")
    endTime: string;   // ISO String (ej: "2026-06-01T23:00:00.000Z")
    durationHours: number;
    color: string | null;
    isNightShift: boolean;
    isEmergencyShift: boolean;
    requiresSpecialization: boolean;
    allowsOvertime: boolean;
    minimumStaffRequired: number;
    isActive: boolean;
    shiftTemplateId?: string;
}

export interface ScheduleEntry {
    id: string;
    scheduleId: string;
    shiftId: string;
    date: string; // ISO String de la fecha del turno
    status: ScheduleEntryStatus;
    nurseId: string | null;
    notes: string | null;
    isEmergencyCoverage: boolean;
    nurse?: {
        id: string;
        user: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
        };
    } | null;
    shift: Shift;
    schedule: Schedule;
    shiftTemplate?: {
        name: string;
        department: {
            name: string;
            description: string | null;
        };
    };
}

export interface Schedule {
    id: string;
    organizationId: string;
    departmentId: string;
    month: number;
    year: number;
    status: ScheduleStatus;
    hasConflicts: boolean;
    totalConflicts: number;
    publishedAt?: string | null;
    autoGenerated?: boolean;
    scheduleEntries?: ScheduleEntry[];
}

export const typeStyles: Record<string, string> = {
    MORNING: "text-amber-700 bg-amber-50 border-amber-200",
    AFTERNOON: "text-blue-700 bg-blue-50 border-blue-200",
    NIGHT: "text-purple-700 bg-purple-50 border-purple-200",
    FULL_DAY: "text-slate-700 bg-slate-100 border-slate-300",
    ON_CALL: "text-indigo-700 bg-indigo-50 border-indigo-200",
    EMERGENCY: "text-red-700 bg-red-50 border-red-200 animate-pulse",
    WEEKEND: "text-emerald-700 bg-emerald-50 border-emerald-200",
    HOLIDAY: "text-rose-700 bg-rose-50 border-rose-200",
    UNKNOWN: "text-gray-600 bg-gray-50 border-gray-200",
};
